require 'rspec/core/rake_task'

task :default => :run

desc "Run connect_four tests"
task :run do 
	ruby "-w lib/connect_four.rb"
end

desc "Run tests on connect_four"
RSpec::Core::RakeTask.new(:spec) do |t|
	t.rspec_opts = "-c -w"
	t.verbose = false
end