require 'rspec/core/rake_task'

task :default => :run

desc "Run tic_tac_toe tests"
task :run do 
	ruby "-w lib/tic_tac_toe.rb"
end

desc "Run tests on tic_tac_toe"
RSpec::Core::RakeTask.new(:spec) do |t|
	t.rspec_opts = "-c -w"
	t.verbose = false
end